# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NO2 // Playbook
email: team@no2.co
description: > # this means to ignore newlines until "baseurl:"
  Guides, resources, and best practices on how to run our agency.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://playbook.no2.com" # the base hostname & protocol for your site
twitter_username: no2co
github_username:  peterberwind

# Build settings
markdown: kramdown
